openapi: 3.0.0
info:
  version: 1.0.0
  title: Notification API
  description: API that uses a notification management PT. XYZ Loan Apps
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://xyzloan.com/notification-service/v1/
paths:
  /notification:
    get:
      tags:
        - Notification
      summary: Search 'Notification' by seacrh criteria.
      description: Search 'Notification' by seacrh criteria.
      operationId: findNotification
      parameters:
        - name: filters
          in: query
          description: "Query parameter to specify search filters. Attribute filters are specified in the following way- 
            ?filters=[attributeName][operator][value].
            ex. 
            ?filters=notificationType==register;
          "
          schema:
            type: string
        - name: page
          in: query
          description: "Requested number of page"
          schema:
            type: string
        - name: limit
          in: query
          description: " Requested number of record to be provided in the response requested by client
            - Default value if not passed : 20
            - Maximum value supported 200"
          schema:
            type: string
        - name: sort
          in: query
          description: "Sort attribute
          ex. 
          sort=notificationType&sort=DESC"
          schema:
            type: string
            
      responses:
        '200':
          description: Get Notification Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Notification
      summary: Creates a New Notification.
      description: Creates a New Notification.
      operationId: createLoanProduct
      requestBody:
        description: API to Create New Notification
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNotification'
      parameters:
        - name: Token
          in: query
          description: Token Generation
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          description: Local of the client
          required: false
          schema:
            type: string

      responses:
        '201':
          description: Create Request Loan Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /notification/{id}:
    get:
      tags:
        - Notification
      summary: Retrieves a 'Notification' by identifier
      description: Retrieves a 'Notification' by identifier
      operationId: retrieveNotification
      parameters:
        - name: id
          in: path
          description: ID of Notification to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retrieve Notification Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /notificationTemplate:
    get:
      tags:
        - Notification Template
      summary: Search 'Notification Template' by seacrh criteria.
      description: Search 'Notification Template' by seacrh criteria.
      operationId: findNotification
      parameters:
        - name: filters
          in: query
          description: "Query parameter to specify search filters. Attribute filters are specified in the following way- 
            ?filters=[attributeName][operator][value].
            ex. 
            ?filters=notificationType==register;
          "
          schema:
            type: string
        - name: page
          in: query
          description: "Requested number of page"
          schema:
            type: string
        - name: limit
          in: query
          description: " Requested number of record to be provided in the response requested by client
            - Default value if not passed : 20
            - Maximum value supported 200"
          schema:
            type: string
        - name: sort
          in: query
          description: "Sort attribute
          ex. 
          sort=notificationType&sort=DESC"
          schema:
            type: string
            
      responses:
        '200':
          description: Get Notification Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotificationTemplate'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  
  /notificationTemplate/{id}:
    put:
      tags:
        - Notification Template
      summary: Updates partially a 'Notification Template' by identifier
      description: |
        Update partially a 'Notification Template' by identifier.
        
        Supported paths and corresponding operations for update elements
        
        - /content
        - /notificationType
        - /status
        - /updatedBy
        - /updatedAt
      operationId: updateNotificationTemplate
      parameters:
        - name: id
          in: path
          description: ID of Notification Template to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Update Notification Template Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationTemplate'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Notification:
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
      required:
          - notificationId
          - customerId
          - notificationTemplateId
          - created_at
          - status
      properties:
            notificationId:
              type: string
            customer_id:
              type: string
            notificationTemplate:
              type: array
              items:
                $ref: '#/components/schemas/NotificationTemplate'
            status:
              type: string
            created_at:
              type: string

    CreateNotification:
      type: object
      required:
          - customerId
          - notificationTemplateId
          - created_at
          - status
      properties:
            customer_id:
              type: string
            notificationTemplateId:
              type: string
            status:
              type: string
            created_at:
              type: string

   
    NotificationTemplate:
      type: object
      required:
          - notificationTemplateId
          - content
          - notificationType
          - status
          - created_by
          - created_at
          - updated_by
          - updated_at
      properties:
            notificationTemplateId:
              type: string
            content:
              type: string
            notificationType:
              type: string
            status:
              type: string
            created_by:
              type: string
            created_at:
              type: string
            updated_by:
              type: string
            updated_at:
              type: string

  
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
