openapi: 3.0.0
info:
  version: 1.0.0
  title: Payment API
  description: API that uses a Payment Management PT. XYZ Loan Apps
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://xyzloan.com/payment-service/v1/
paths:
  /payment:
    get:
      tags:
        - Payment
      summary: Search 'Payment' by seacrh criteria.
      description: Search 'Payment' by seacrh criteria.
      operationId: findPayment
      parameters:
        - name: filters
          in: query
          description: "Query parameter to specify search filters. Attribute filters are specified in the following way- 
            ?filters=[attributeName][operator][value].
            ex. 
            ?filters=paymentStatus==failed;
          "
          schema:
            type: string
        - name: page
          in: query
          description: "Requested number of page"
          schema:
            type: string
        - name: limit
          in: query
          description: " Requested number of record to be provided in the response requested by client
            - Default value if not passed : 20
            - Maximum value supported 200"
          schema:
            type: string
        - name: sort
          in: query
          description: "Sort attribute
          ex. 
          sort=notificationType&sort=DESC"
          schema:
            type: string
            
      responses:
        '200':
          description: Get Payment Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Payment
      summary: Creates a New Payment.
      description: Creates a New Payment.
      operationId: createPayment
      requestBody:
        description: API to Create New Payment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayment'
      parameters:
        - name: Token
          in: query
          description: Token Generation
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          description: Local of the client
          required: false
          schema:
            type: string

      responses:
        '201':
          description: Create Payment Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetail'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /payment/{id}:
    get:
      tags:
        - Payment
      summary: Retrieves a 'Payment' by identifier
      description: Retrieves a 'Payment' by identifier
      operationId: retrievePayment
      parameters:
        - name: id
          in: path
          description: ID of Payment to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retrieve Payment Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetail'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    Payment:
      allOf:
        - $ref: '#/components/schemas/Payment'
        - type: object
      required:
          - paymentId
          - loanId
          - paymentDate
          - amount
          - status
      properties:
            paymentId:
              type: string
            loanId:
              type: string
            paymentDate:
              type: string
            amount:
              type: string
            status:
              type: string

    PaymentDetail:
      type: object
      required:
          - paymentId
          - loanId
          - paymentDate
          - amount
          - status
      properties:
            paymentId:
              type: string
            loanId:
              type: string
            paymentDate:
              type: string
            amount:
              type: string
            status:
              type: string
            loan:
              type: array
              items:
                $ref: '#/components/schemas/Loan'

    CreatePayment:
      type: object
      required:
          - paymentId
          - loanId
          - paymentDate
          - amount
          - status
      properties:
            loanId:
              type: string
            paymentDate:
              type: string
            amount:
              type: string
            status:
              type: string

    Loan:
      type: object
      required:
          - loanId
          - customerId
          - loanProductId
          - loanTenor
          - loanAmount
          - orderDate
          - status
      properties:
            loanId:
              type: string
            customerId:
              type: string
            loanProductId:
              type: string
            loanTenor:
              type: string
            loanAmount:
              type: string
            orderDate:
              type: string
            status:
              type: string
   
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
